# Generated by Django 4.1 on 2022-08-28 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='ChatRoom',
        ),
    ]
