# Generated by Django 4.1 on 2022-08-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_room_chatroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='meeting_duration',
            field=models.PositiveIntegerField(default=30, help_text='in minutes'),
        ),
        migrations.AlterField(
            model_name='roomagenda',
            name='time',
            field=models.PositiveBigIntegerField(help_text='in minutess'),
        ),
    ]
